---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort          # simple for local clusters; change to LoadBalancer in cloud
  selector:
    app: flask
  ports:
    - port: 5000
      targetPort: 5000
      # nodePort: 30007    # optional: leave out to let k8s choose a port
